MyPet/MyPet/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from board import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('common/', include('common.urls')),
]

MyPet/MyPet/board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:postId>/', views.detail, name='detail'),
    path('answer/create/<int:postId>/', views.answer_create, name='answer_create'),
]

MyPet/MyPet/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('signup/', views.signup, name='signup'),
]

MyPet/MyPet/board/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    writer = models.CharField(max_length=20)
    date = models.DateTimeField()
    
    def __str__(self):
        return self.title

class Answer(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    writer = models.CharField(max_length=20)
    date = models.DateTimeField()
    
    def __str__(self):
        return self.title
# Create your models here.

MyPet/MyPet/common/models.py
from django.db import models

# Create your models here.

MyPet/MyPet/common/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("username", "email", "password")

MyPet/MyPet/board/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Post

from django.http import HttpResponse


def index(request):
    # 게시물 목록 출력
    postList = Post.objects.order_by('-date')
    context = {'postList': postList}
    return render(request, 'board/list.html', context)

def detail(request, postId):
    # 상세보기
    post = Post.objects.get(id=postId)
    context = {'post': post}
    return render(request, 'board/detail.html', context)

def answer_create(request, postId):
    # 답글 추가
    post = get_object_or_404(Post, pk=postId)
    post.answer_set.create(content=request.POST.get('content'), date=timezone.now())
    return redirect('board:detail', postId=postId)

MyPet/MyPet/common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from .forms import UserForm


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

MyPet/MyPet/templates/board/detail.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jua&display=swap" rel="stylesheet">
    <style>
        * {
            font-family: 'Jua', sans-serif;
        }
        .center {
            text-align: center;
        }
    </style>
<div class="container my-3">
    <h2 class="border-bottom py-2">{{ post.title }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ post.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">{{ post.date }}</div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{post.answer_set.count}}개의 댓글이 있습니다.</h5>
    {% for answer in post.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">{{ answer.date }}</div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'board:answer_create' post.id %}" method="post" class="my-3">
        {% csrf_token %}
        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="댓글 등록" class="btn btn-primary">
    </form>
</div>

MyPet/MyPet/templates/board/list.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>My Pet</title>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jua&display=swap" rel="stylesheet">
    <style>
        * {
            font-family: 'Jua', sans-serif;
        }
        .center {
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="container my-3">
        <h1 class="center">My Pet</h1>
        <div class="d-flex justify-content-end my-3">
            <a href="{% url 'common:login' %}" class="btn btn-primary mx-2">로그인</a>
        </div>
        <table class="table">
            <thead>
                <tr class="thead-dark">
                    <th>번호</th><th>제목</th><th>작성일시</th><th>작성자</th>
                </tr>
            </thead>
            <tbody>
            {% if postList %}
            {% for post in postList %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td><a href="{% url 'board:detail' post.id %}">{{ post.title }}</a></td>
                <td>{{ post.date }}</td>
                <td>{{ post.writer }}</td>
            </tr>
            {% endfor %}
            {% else %}
            <tr><td colspan="3">게시물이 없습니다.</td></tr>
            {% endif %}
            </tbody>
        </table>
    </div>
</body>
</html>

MyPet/MyPet/templates/common/login.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

<div class="container my-3">
    <form method="post" class="post-form" action="{% url 'common:login' %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">아이디</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <div class="row">
            <div class="col-4">
                <button type="submit" class="btn btn-primary">로그인</button>        
            </div>
            <div class="col-8 text-right">
                 <a href="{%url 'common:signup' %}">회원가입</a>
            </div>            
        </div>   
    </form>
</div>

MyPet/MyPet/templates/common/signup.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>계정생성</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:login' %}">로그인 하세요.</a></span>
        </div>
    </div>
    <form method="post" action="{% url 'common:signup' %}" class="post-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>